---
- name: "Copy binary"
  ansible.builtin.copy:
    src: go-apt-cacher
    dest: "{{ go_apt_cacher_binary_path }}"
    owner: "{{ go_apt_cacher_user }}"
    group: "{{ go_apt_cacher_group }}"
    mode: '0755'
  notify: "Restart go-apt-cacher"

- name: "Copy configuration"
  ansible.builtin.copy:
    content: "{{ go_apt_cacher_config }}"
    dest: "{{ go_apt_cacher_config_path }}"
    owner: "{{ go_apt_cacher_user }}"
    group: "{{ go_apt_cacher_group }}"
    mode: '0644'
  notify: "Restart go-apt-cacher"

- name: "Create systemd"
  ansible.builtin.template:
    src: 'go-apt-cacher.service.j2'
    dest: '/etc/systemd/system/go-apt-cacher.service'
    mode: '0640'
  notify: "Restart go-apt-cacher"

- name: "Enable and Start go-apt-cacher.service"
  ansible.builtin.service:
    name: go-apt-cacher
    state: started
    enabled: true
    daemon_reload: true
